INSERT INTO weather_icons(id, main, description, icon) VALUES ('200','Thunderstorm','thunderstorm with light rain','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('201','Thunderstorm','thunderstorm with rain','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('202','Thunderstorm','thunderstorm with heavy rain','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('210','Thunderstorm','light thunderstorm','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('211','Thunderstorm','thunderstorm','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('212','Thunderstorm','heavy thunderstorm','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('221','Thunderstorm','ragged thunderstorm','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('230','Thunderstorm','thunderstorm with light drizzle','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('231','Thunderstorm','thunderstorm with drizzle','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('232','Thunderstorm','thunderstorm with heavy drizzle','11d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('300','Drizzle','light intensity drizzle','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('301','Drizzle','drizzle','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('302','Drizzle','heavy intensity drizzle','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('310','Drizzle','light intensity drizzle rain','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('311','Drizzle','drizzle rain','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('312','Drizzle','heavy intensity drizzle rain','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('313','Drizzle','shower rain and drizzle','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('314','Drizzle','heavy shower rain and drizzle','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('321','Drizzle','shower drizzle','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('500','Rain','light rain','10d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('501','Rain','moderate rain','10d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('502','Rain','heavy intensity rain','10d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('503','Rain','very heavy rain','10d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('504','Rain','extreme rain','10d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('511','Rain','freezing rain','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('520','Rain','light intensity shower rain','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('521','Rain','shower rain','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('522','Rain','heavy intensity shower rain','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('531','Rain','ragged shower rain','09d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('600','Snow','light snow','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('601','Snow','Snow','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('602','Snow','Heavy snow','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('611','Snow','Sleet','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('612','Snow','Light shower sleet','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('613','Snow','Shower sleet','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('615','Snow','Light rain and snow','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('616','Snow','Rain and snow','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('620','Snow','Light shower snow','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('621','Snow','Shower snow','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('622','Snow','Heavy shower snow','13d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('701','Mist','mist','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('711','Smoke','Smoke','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('721','Haze','Haze','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('731','Dust','sand/ dust whirls','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('741','Fog','fog','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('751','Sand','sand','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('761','Dust','dust','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('762','Ash','volcanic ash','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('771','Squall','squalls','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('781','Tornado','tornado','50d');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('800','Clear','clear sky','01d,01n');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('801','Clouds','few clouds: 11-25%','02d,02n');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('802','Clouds','scattered clouds: 25-50%','03d,03n');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('803','Clouds','broken clouds: 51-84%','04d,04n');
INSERT INTO weather_icons(id, main, description, icon) VALUES ('804','Clouds','overcast clouds: 85-100%','04d,04n');
