package jp.co.stnet.apps.domain.repository;

import jp.co.stnet.apps.domain.model.Authorities;

public interface AuthoritiesRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.authorities
     *
     * @mbg.generated
     */
    int insert(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.authorities
     *
     * @mbg.generated
     */
    int insertSelective(Authorities record);
}