package jp.co.stnet.apps.domain.repository;

import jp.co.stnet.apps.domain.model.Authorities;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AuthoritiesRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.authorities
     *
     * @mbg.generated
     */
    int insert(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.authorities
     *
     * @mbg.generated
     */
    int insertSelective(Authorities record);

    /**
     * @param username
     * @return
     */
    Authorities selectByPrimaryKey(@Param("username") String username);
}
