package jp.co.stnet.apps.domain.repository;

import jp.co.stnet.apps.domain.model.Users;

import java.util.List;

public interface UsersRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbg.generated
     */
    Users selectByPrimaryKey(String username);

    List<Users> selectAll();
}
